export const translations = {
  en: {
    horario: "Hours",
    delunesaviernes: "From Monday to Friday",
    direccion: "Paseo Landabarri, 48",
    localidad: "Leioa | Biscay, 48940",
    telefono: "+34 944 33 17 36",
    telefono2: "+ 34 650 56 77 12",
    emailaddress: "info@inmoartaza.es",
    tasaciontitulo: "Request a free valuation of your property<br/>with Artaza Inmobiliaria",
    tasaciontexto: "If you're thinking of selling, we offer you a free property valuation.",
    registrate: "Valuation",
    // lunesajueves: "Monday – Thursday",
    lunesajueves: "Mornings",
    // viernes: "Friday",
    viernes: "Afternoons",
    mananas: "10:30 AM – 1:30 PM",
    tardes: "5:00 PM – 8:00 PM",
    viernesTarde: "Friday by appointment only",
    nombreempresa: "Artaza Real Estate",

    visit: "Visit us",
    cookies: "Cookies",
    privacy: "Privacy",
    terms: "Terms",
    legal: "Legal",
    c: "© 2025 Artaza Real Estate.",
    madeBy: "Made by",
    menu: "Menu",
    writeus: "Write to us",
    callus: "Call us",

  },
  es: {
    horario: "Horario",
    delunesaviernes: "De Lunes a Viernes",
    direccion: "Paseo Landabarri, 48",
    localidad: "Leioa | Vizcaya, 48940",
    telefono: "944 33 17 36",
    telefono2: "650 56 77 12",
    emailaddress: "info@inmoartaza.es",
    tasaciontitulo: "Solicita una valoración gratuita de tu propiedad<br/>con Artaza Inmobiliaria",
    tasaciontexto: "Si estás pensando en vender, te hacemos una tasación gratuita.",
    registrate: "Tasación",
    // lunesajueves: "Lunes – Jueves",
    lunesajueves: "Mañanas",
    // viernes: "Viernes",
    viernes: "Tardes",
    mananas: "10:30 – 13:30",
    tardes: "17:00 – 20:00",
    viernesTarde: "Viernes con cita previa",
    nombreempresa: "Artaza Inmobiliaria",

    visit: "Visítanos",
    cookies: "Cookies",
    privacy: "Privacidad",
    terms: "Términos",
    legal: "Legal",
    c: "© 2025 Inmobiliaria Artaza.",
    madeBy: "Hecho por",
    menu: "Menú",
    writeus: "Escríbenos",
    callus: "LLámanos",

  }
};