export const translations = {
  en: {
    horario: "Hours",
    delunesaviernes: "From Monday to Friday",
    direccion: "Paseo Landabarri, 48",
    localidad: "Leioa | Biscay, 48940",
    telefono: "+34 944 33 17 36",
    emailaddress: "info@inmoartaza.es",
    tasaciontitulo: "What's your house worth?",
    tasaciontexto: "If you're thinking of selling, we offer you a free property valuation.",
    registrate: "Valuation",
    lunesajueves: "Monday – Thursday",
    viernes: "Friday",
    mananas: "10:30 AM – 1:30 PM",
    tardes: "5:00 PM – 8:00 PM",
    nombreempresa: "Artaza Real Estate",

    visit: "Visit",
    cookies: "Cookies",
    privacy: "Privacy",
    terms: "Terms",
    legal: "Legal",
    c: "© 2025 Artaza Real Estate.",
  },
  es: {
    horario: "Horario",
    delunesaviernes: "De Lunes a Viernes",
    direccion: "Paseo Landabarri, 48",
    localidad: "Leioa | Vizcaya, 48940",
    telefono: "944 33 17 36",
    emailaddress: "info@inmoartaza.es",
    tasaciontitulo: "¿Cuánto vale tu casa?",
    tasaciontexto: "Si estás pensando en vender, te hacemos una tasación gratuita.",
    registrate: "Tasación",
    lunesajueves: "Lunes – Jueves",
    viernes: "Viernes",
    mananas: "10:30 – 13:30",
    tardes: "17:00 – 20:00",
    nombreempresa: "Artaza Inmobiliaria",

    visit: "Visita",
    cookies: "Cookies",
    privacy: "Privacidad",
    terms: "Términos",
    legal: "Legal",
    c: "© 2025 Inmobiliaria Artaza.",
  }
};