export const homeTranslations = {
    en: {
      tituloprincipal: "Turning <em>local knowledge</em><br/>into magic",
      subtitulo: "Helping you find your perfect space for over a decade",
      subtitulo2: "Artaza<br/>Real Estate",
      textosubtitulo2: "Artaza Real Estate is an agency specialized in the property market of Artaza and Getxo. With over 10 years of experience and a local office, we have deep knowledge of the community.<br/>This allows us to help sellers close deals quickly and efficiently, while giving buyers access to some of the area’s finest properties.",
      artaza: "A Stroll Around the area",
      botonquienessomos: "About us",
      propiedadesLand: "Local experts",
      textopropiedadesLand: "We are a deeply local agency, with exceptional knowledge of each area in which we operate. What sets us apart is our ability to thoroughly understand the surroundings, the market, and the community before every sale. Decades of experience back us in connecting discerning property owners with the right buyers.<br/>This allows us to offer honest, personalized, and effective advice. More than selling properties, we create unique experiences rooted in the true value of what’s local.",
      botonproperties: "Our Properties",
      botonproperties2: "Sell with us",
      compratitulo: "Your <em>dream home</em><br/>is just a step away",
      textocompra: "",
    },
    es: {
      tituloprincipal: "Convirtiendo el <em>saber local</em><br/>en magia",
      subtitulo: "Más de una década ayudándote a encontrar tu espacio ideal",
      subtitulo2: "Artaza<br/>Inmobiliaria",
      textosubtitulo2: "Artaza Inmobiliaria es una agencia especializada en el mercado inmobiliario de Artaza</em> y Getxo. Con más de 10 años de experiencia y sede en la zona, contamos con un profundo conocimiento de la comunidad local.<br/>Esto nos permite ayudar a los vendedores a cerrar operaciones de manera rápida y eficaz, y ofrecer a los compradores acceso a algunas de las mejores propiedades de la zona.",
      artaza: "Un paseo por la zona",
      botonquienessomos: "Conócenos",
      propiedadesLand: "El valor<br/>de lo local",
      textopropiedadesLand: "Somos una agencia profundamente local, con un conocimiento excepcional de cada zona en la que operamos. Nos distingue la capacidad de entender a fondo el entorno, el mercado y la comunidad antes de cada venta.<br/>Décadas de experiencia nos avalan uniendo propietarios exigentes con los compradores adecuados. Más que vender propiedades, creamos experiencias únicas ancladas en el auténtico valor de lo local.",
      botonproperties: "Nuestras Propiedades",
      botonproperties2: "Vende con nosotros",
      compratitulo: "Tu <em>hogar soñado</em><br/>está a un solo paso",
      textocompra: "",
    }
  };