export const homeTranslations = {
    en: {
      tituloprincipal: "Turning <em>local knowledge</em><br/>into magic",
      subtitulo: "Helping you find your perfect space for over a decade",
      subtitulo2: "Artaza<br/>Real Estate",
      textosubtitulo2: "Artaza Real Estate is an agency specialized in the property market of Artaza and Getxo. With over 10 years of experience and a local office, we have deep knowledge of the community.<br/><br/>This allows us to help sellers close deals quickly and efficiently, while giving buyers access to some of the area’s finest properties.",
      artaza: "A Stroll Around the area",
      botonquienessomos: "About us",
      propiedadesLand: "Local experts",
      textopropiedadesLand: "At Artaza Real Estate, we take pride in being a truly local real estate agency, specialized in the Artaza, Getxo, and northern Spain area.<br />We know the market, its rhythms, and its people like no one else.<br />This allows us to offer rigorous, honest, and fully personalized advice.<br />Our approach is close, discreet, and committed: we listen carefully, pay attention to every detail, and accompany our clients with the utmost confidentiality.<br />We value relationships based on trust and always act with integrity, putting our experience at the service of those who rely on us.<br />More than managing properties, we create tailored experiences.",
      botonproperties: "Properties",
      botonproperties2: "Tell us what you're looking for",
      compratitulo: "Your <em>dream home</em><br/>is just a step away",
      textocompra: "",
    },
    es: {
      tituloprincipal: "Convirtiendo el <em>saber local</em><br/>en magia",
      subtitulo: "Más de una década ayudándote a encontrar tu espacio ideal",
      subtitulo2: "Inmobiliaria<br/>Artaza",
      textosubtitulo2: "Inmobiliria Artaza es una agencia especializada en el mercado inmobiliario de Artaza</em> y Getxo. Con más de 10 años de experiencia y sede en la zona, contamos con un profundo conocimiento de la comunidad local.<br/><br/>Esto nos permite ayudar a los vendedores a cerrar operaciones de forma rápida y eficaz, y ofrecer a los compradores acceso a algunas de las mejores propiedades de la zona.",
      artaza: "Un paseo por la zona",
      botonquienessomos: "Conócenos",
      propiedadesLand: "Expertos en lo local",
      textopropiedadesLand: "En Artaza Inmobiliaria nos enorgullece ser una inmobiliaria profundamente local, especializada en el entorno de Artaza, Getxo y el norte de España.<br />Conocemos el mercado, sus ritmos y su gente como nadie más.<br />Esto nos permite ofrecer un asesoramiento riguroso, honesto y totalmente adaptado a cada persona.<br />Nuestro enfoque es cercano, discreto y comprometido: escuchamos con atención, cuidamos cada detalle y acompañamos a nuestros clientes con la máxima confidencialidad.<br />Valoramos las relaciones basadas en la confianza y actuamos siempre con integridad, poniendo nuestra experiencia al servicio de quienes confían en nosotros.<br />Más que gestionar propiedades, creamos experiencias a medida.",
      botonproperties: "Propiedades",
      botonproperties2: "Define tus criterios de compra",
      compratitulo: "Tu <em>hogar soñado</em><br/>está a un solo paso",
      textocompra: "",
    }
  };