export const IndividualHome = {
    en: {
        propertyNotFound: "Property not found",
        propertyNotFoundMessage: "The property you are looking for does not exist or has been removed.",
        description: "Description",
        extras: "Extras",
        terrace: "Terrace",
        balcony: "Balcony",
        builtInWardrobes: "Built-in wardrobes",
        storageRoom: "Storage room",
        garage: "Garage",
        pool: "Pool",
        garden: "Garden",
        privateUrbanization: "Private urbanization",
        chimney: "Chimney",
        txoko: "Txoko",
        laundry: "Laundry room",
        attic: "Attic",
        elevator: "Elevator",
        yearBuilt: "Year built",
        parcelM2: "Plot size",
        description: "Description",
        extras: "Extras",
    },
    es: {
        propertyNotFound: "Propiedad no encontrada",
        propertyNotFoundMessage: "La propiedad que buscas no existe o ha sido eliminada.",
        description: "Descripción",
        extras: "Extras",
        terrace: "Terraza",
        balcony: "Balcón",
        builtInWardrobes: "Armarios empotrados",
        storageRoom: "Trastero",
        garage: "Garaje",
        pool: "Piscina",
        garden: "Jardín",
        privateUrbanization: "Urbanización privada",
        chimney: "Chimenea",
        txoko: "Txoko",
        laundry: "Lavadero",
        attic: "Ático",
        elevator: "Ascensor",
        yearBuilt: "Año de construcción",
        parcelM2: "Superficie parcela",
        description: "Descripción",
        extras: "Extras",
    }
};