export const IndividualHome = {
    en: {
        propertyNotFound: "Property not found",
        propertyNotFoundMessage: "The property you are looking for does not exist or has been removed.",
        description: "Description",
        extras: "Extras",
        terrace: "Terrace",
        balcony: "Balcony",
        builtInWardrobes: "Built-in wardrobes",
        storageRoom: "Storage room",
        garage: "Garage",
        pool: "Pool",
        garden: "Garden",
        chimney: "Chimney",
        txoko: "Txoko",
        laundry: "Laundry room",
        attic: "Attic",
        elevator: "Elevator",
        parcelM2: "Plot size",
        description: "Description",
        extras: "Extras",
        features: "Features",

        builtM2: "Built Area",
        usableM2: "Usable Area",
        bedroomsP: "Bedrooms",
        bathrooms: "Bathrooms",
        orientation: "Orientation",
        privateUrbanization: "Private urbanization",
        yearBuilt: "Year built",
        homeType: "Property type",

        address: "Address",
        price: "Price",
        location: "Location",
        sold: "Sold",

        previousProperty: "Previous Property",
        nextProperty: "Next Property",

        aboutThisPropertyFirstLine: "About this",
        aboutThisPropertySecondLine: "Property",

        aboutItsLocationFirstLine: "Location and",
        aboutItsLocationSecondLine: "Surroundings",

        similarPropertiesFirstLine: "Similar",
        similarPropertiesSecondLine: "Options",

    },
    es: {
        propertyNotFound: "Propiedad no encontrada",
        propertyNotFoundMessage: "La propiedad que buscas no existe o ha sido eliminada.",
        description: "Descripción",
        extras: "Extras",
        terrace: "Terraza",
        balcony: "Balcón",
        builtInWardrobes: "Armarios empotrados",
        storageRoom: "Trastero",
        garage: "Garaje",
        pool: "Piscina",
        garden: "Jardín",
        chimney: "Chimenea",
        txoko: "Txoko",
        laundry: "Lavadero",
        attic: "Ático",
        elevator: "Ascensor",
        parcelM2: "Superficie parcela",
        description: "Descripción",
        extras: "Extras",
        features: "Características",


        builtM2: "m2 construidos",
        usableM2: "m2 usables",
        bedroomsP: "Dormitorios",
        bathrooms: "Baños",
        orientation: "Orientación",
        privateUrbanization: "Urbanización privada",
        yearBuilt: "Año de construcción",        
        homeType: "Tipo de Vivienda",

        address: "Dirección",
        price: "Precio",
        location: "Ubicación",
        sold: "Vendido",

        previousProperty: "Propiedad Anterior",
        nextProperty: "Siguiente Propiedad",

        aboutThisPropertyFirstLine: "Sobre esta",
        aboutThisPropertySecondLine: "Propiedad",

        aboutItsLocationFirstLine: "Entorno y",
        aboutItsLocationSecondLine: "Ubicación",

        similarPropertiesFirstLine: "Opciones",
        similarPropertiesSecondLine: "Similares",
    }
};